version: '3'

services:
  spring-boot-app:
    image: 'spring-user-crud:1.0.0'
    build:
      context: .
    container_name: spring-boot-app
    restart: 'on-failure'
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/explorespring
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  mysql-db:
    image: 'mysql:latest'
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=explorespring
